repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
        name: Check JSON syntax
      - id: pretty-format-json
        name: Format JSON files
        args: ['--autofix', '--indent=2']
        files: \.json$
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
